enum TribeName {
    // North = 'North',
    // Northeast = 'Northeast',
    // East = 'East',
    // Southeast = 'Southeast',
    // South = 'South',
    // Southwest = 'Southwest',
    // West = 'West',
    // Northwest = 'Northwest',

    Saami = 'Saami',
    Chukchi = 'Chukchi',
    Chinese = 'Chinese',
    Javanese = 'Javanese',
    Zulu = 'Zulu',
    Latins = 'Latins',
    Lakota = 'Lakota',
    Aleut = 'Aleut',
    Eskimo = 'Eskimo',
    Inuit = 'Inuit',

    Copts = 'Copts',
    Goths = 'Goths',
    Britons = 'Britons',
    Celts = 'Celts',
    Gauls = 'Gauls',
    Krivichs = 'Krivichs',
    Dorians = 'Dorians',
    Ionians = 'Ionians',
    Spartans = 'Spartans',

    Achaeans = 'Achaeans',
    Aeolians = 'Aeolians',
    Thessalians = 'Thessalians',
    Attics = 'Attics',
    Corinthians = 'Corinthians',
    Cretans = 'Cretans',
    Macedonians = 'Macedonians',
    Anatolians = 'Anatolians',
    Phrygians = 'Phrygians',
    Thracians = 'Thracians',
}

export default TribeName
